// DO NOT EDIT!
// Automatically generated by xcdl for 'micro-os-plus.utils.lists'. (TODO)

#ifndef MICRO_OS_PLUS_MICRO_TEST_PLUS_DEFINES_H_
#define MICRO_OS_PLUS_MICRO_TEST_PLUS_DEFINES_H_

// Display trace messages in the µTest++ testing framework when TRACE is
// enabled.
#if !defined(MICRO_OS_PLUS_MICRO_TEST_PLUS_TRACE_ENABLED)
// #define MICRO_OS_PLUS_MICRO_TEST_PLUS_TRACE_ENABLED
#endif // MICRO_OS_PLUS_MICRO_TEST_PLUS_TRACE_ENABLED

// Display trace messages in constructors and destructors in the µTest++
// testing framework when TRACE is enabled.
#if !defined(MICRO_OS_PLUS_MICRO_TEST_PLUS_TRACE_CONSTRUCTORS_ENABLED)
// #define MICRO_OS_PLUS_MICRO_TEST_PLUS_TRACE_CONSTRUCTORS_ENABLED
#endif // MICRO_OS_PLUS_MICRO_TEST_PLUS_TRACE_CONSTRUCTORS_ENABLED

#endif // MICRO_OS_PLUS_MICRO_TEST_PLUS_DEFINES_H_
