// DO NOT EDIT!
// Automatically generated by xcdl. (TODO)

// ----------------------------------------------------------------------------

#ifndef MICRO_OS_PLUS_ARCHITECTURE_DEFINES_H_
#define MICRO_OS_PLUS_ARCHITECTURE_DEFINES_H_

// ----------------------------------------------------------------------------

// The RISC-V architecture definitions.
#if !defined(MICRO_OS_PLUS_ARCHITECTURES_RISCV_ENABLED)
#define MICRO_OS_PLUS_ARCHITECTURES_RISCV_ENABLED
#endif // !defined(MICRO_OS_PLUS_ARCHITECTURES_RISCV_ENABLED)

// The ELF entry point when the application is started by a debuggger.
#if !defined(MICRO_OS_PLUS_ARCHITECTURES_RISCV_DEBUGGER_ENTRY_POINT_ENABLED)
// #define MICRO_OS_PLUS_ARCHITECTURES_RISCV_DEBUGGER_ENTRY_POINT_ENABLED
#endif // !defined(MICRO_OS_PLUS_ARCHITECTURES_RISCV_DEBUGGER_ENTRY_POINT_ENABLED)

// The reset handler executed when the system is reset.
#if !defined(MICRO_OS_PLUS_ARCHITECTURES_RISCV_RESET_ENTRY_ENABLED)
#define MICRO_OS_PLUS_ARCHITECTURES_RISCV_RESET_ENTRY_ENABLED
#endif // !defined(MICRO_OS_PLUS_ARCHITECTURES_RISCV_RESET_ENTRY_ENABLED)

// ----------------------------------------------------------------------------

#endif // MICRO_OS_PLUS_ARCHITECTURE_DEFINES_H_

// ----------------------------------------------------------------------------
