// DO NOT EDIT!
// Automatically generated by xcdl. (TODO)

// ----------------------------------------------------------------------------

#ifndef MICRO_OS_PLUS_DEVICE_DEFINES_H_
#define MICRO_OS_PLUS_DEVICE_DEFINES_H_

// ----------------------------------------------------------------------------

#if !defined(MICRO_OS_PLUS_DEVICES_RASPBERRY_PI_ENABLED)
#define MICRO_OS_PLUS_DEVICES_RASPBERRY_PI_ENABLED
#endif // !defined(MICRO_OS_PLUS_DEVICES_RASPBERRY_PI_ENABLED)

#if !defined(MICRO_OS_PLUS_DEVICES_RASPBERRY_PI_CORE_RP2350_RISCV)
#define MICRO_OS_PLUS_DEVICES_RASPBERRY_PI_CORE_RP2350_RISCV
#endif // !defined(MICRO_OS_PLUS_DEVICES_RASPBERRY_PI_CORE_RP2350_RISCV)

#if !defined(MICRO_OS_PLUS_DEVICES_RASPBERRY_PI_VECTORS_RP2350_RISCV_ENABLED)
#define MICRO_OS_PLUS_DEVICES_RASPBERRY_PI_VECTORS_RP2350_RISCV_ENABLED
#endif // !defined(MICRO_OS_PLUS_DEVICES_RASPBERRY_PI_VECTORS_RP2350_RISCV_ENABLED)

#if !defined(MICRO_OS_PLUS_DEVICES_RASPBERRY_PI_SDK_SBRK_ENABLED)
// #define MICRO_OS_PLUS_DEVICES_RASPBERRY_PI_SDK_SBRK_ENABLED
#endif // !defined(MICRO_OS_PLUS_DEVICES_RASPBERRY_PI_SDK_SBRK_ENABLED)

#if !defined(MICRO_OS_PLUS_DEVICES_RASPBERRY_PI_SYSTEM_CLOCK_ENABLED)
#define MICRO_OS_PLUS_DEVICES_RASPBERRY_PI_SYSTEM_CLOCK_ENABLED
#endif // !defined(MICRO_OS_PLUS_DEVICES_RASPBERRY_PI_SYSTEM_CLOCK_ENABLED)

// ----------------------------------------------------------------------------

#endif // MICRO_OS_PLUS_DEVICE_DEFINES_H_

// ----------------------------------------------------------------------------
