// DO NOT EDIT!
// Automatically generated by xcdl. (TODO)

// ----------------------------------------------------------------------------

#ifndef MICRO_OS_PLUS_ARCHITECTURE_DEFINES_H_
#define MICRO_OS_PLUS_ARCHITECTURE_DEFINES_H_

// ----------------------------------------------------------------------------

// The AArch64 architecture definitions.
#if !defined(MICRO_OS_PLUS_ARCHITECTURES_AARCH64_ENABLED)
#define MICRO_OS_PLUS_ARCHITECTURES_AARCH64_ENABLED
#endif // !defined(MICRO_OS_PLUS_ARCHITECTURES_AARCH64_ENABLED)

// ----------------------------------------------------------------------------

#endif // MICRO_OS_PLUS_ARCHITECTURE_DEFINES_H_

// ----------------------------------------------------------------------------
