// DO NOT EDIT!
// Automatically generated by xcdl. (TODO)

// ----------------------------------------------------------------------------

#ifndef MICRO_OS_PLUS_MICRO_TEST_PLUS_DEFINES_H_
#define MICRO_OS_PLUS_MICRO_TEST_PLUS_DEFINES_H_

// ----------------------------------------------------------------------------

// µTest++, a lightweight testing framework for embedded platforms.
#if !defined(MICRO_OS_PLUS_MICRO_TEST_PLUS_ENABLED)
#define MICRO_OS_PLUS_MICRO_TEST_PLUS_ENABLED
#endif // !defined(MICRO_OS_PLUS_MICRO_TEST_PLUS_ENABLED)

// Display trace messages in the µTest++ testing framework when TRACE is
// enabled.
// #if !defined(MICRO_OS_PLUS_MICRO_TEST_PLUS_TRACE_ENABLED)
// #define MICRO_OS_PLUS_MICRO_TEST_PLUS_TRACE_ENABLED
// #endif // !defined(MICRO_OS_PLUS_MICRO_TEST_PLUS_TRACE_ENABLED)

// Display trace messages in constructors and destructors in the µTest++
// testing framework when TRACE is enabled.
// #if !defined(MICRO_OS_PLUS_MICRO_TEST_PLUS_TRACE_CONSTRUCTORS_ENABLED)
// #define MICRO_OS_PLUS_MICRO_TEST_PLUS_TRACE_CONSTRUCTORS_ENABLED
// #endif // !defined(MICRO_OS_PLUS_MICRO_TEST_PLUS_TRACE_CONSTRUCTORS_ENABLED)

// ----------------------------------------------------------------------------

#endif // MICRO_OS_PLUS_MICRO_TEST_PLUS_DEFINES_H_

// ----------------------------------------------------------------------------
