/*
 * This file is part of the µOS++ project (https://micro-os-plus.github.io/).
 * Copyright (c) 2023-2026 Liviu Ionescu. All rights reserved.
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose is hereby granted, under the terms of the MIT license.
 *
 * If a copy of the license was not distributed with this file, it can be
 * obtained from https://opensource.org/licenses/mit.
 */

/*
 * The list of external handlers was automatically generated by
 * processing the files available in the CubeMX packages, the folder:
 * `/Drivers/CMSIS/Device/ST/STM32F?xx/Source/Templates/arm`
 */

// clang-format off
// ----------------------------------------------------------------------------

#include "micro-os-plus/architecture.h"
#include "micro-os-plus/architecture-cortexm/exception-handlers.h"

// ----------------------------------------------------------------------------

void __attribute__((weak))
Default_Handler(void);

/*
 * Forward declaration of the specific IRQ handlers. These are aliased
 * to the Default_Handler, which is a 'forever' loop. When the application
 * defines an actual handler (with the same name), it will automatically
 * take precedence over these weak definitions.
 */

void __attribute__ ((weak, alias ("Default_Handler")))
WWDG_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
PVD_AVD_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
RTC_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
RTC_S_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
TAMP_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
RAMCFG_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
FLASH_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
FLASH_S_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
GTZC_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
RCC_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
RCC_S_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
EXTI0_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
EXTI1_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
EXTI2_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
EXTI3_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
EXTI4_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
EXTI5_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
EXTI6_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
EXTI7_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
EXTI8_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
EXTI9_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
EXTI10_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
EXTI11_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
EXTI12_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
EXTI13_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
EXTI14_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
EXTI15_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
GPDMA1_Channel0_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
GPDMA1_Channel1_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
GPDMA1_Channel2_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
GPDMA1_Channel3_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
GPDMA1_Channel4_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
GPDMA1_Channel5_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
GPDMA1_Channel6_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
GPDMA1_Channel7_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
IWDG_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
SAES_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
ADC1_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
DAC1_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
FDCAN1_IT0_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
FDCAN1_IT1_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
TIM1_BRK_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
TIM1_UP_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
TIM1_TRG_COM_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
TIM1_CC_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
TIM2_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
TIM3_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
TIM4_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
TIM5_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
TIM6_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
TIM7_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
I2C1_EV_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
I2C1_ER_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
I2C2_EV_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
I2C2_ER_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
SPI1_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
SPI2_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
SPI3_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
USART1_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
USART2_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
USART3_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
UART4_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
UART5_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
LPUART1_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
LPTIM1_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
TIM8_BRK_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
TIM8_UP_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
TIM8_TRG_COM_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
TIM8_CC_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
ADC2_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
LPTIM2_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
TIM15_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
USB_DRD_FS_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
CRS_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
UCPD1_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
FMC_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
OCTOSPI1_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
SDMMC1_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
I2C3_EV_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
I2C3_ER_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
SPI4_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
USART6_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
GPDMA2_Channel0_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
GPDMA2_Channel1_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
GPDMA2_Channel2_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
GPDMA2_Channel3_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
GPDMA2_Channel4_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
GPDMA2_Channel5_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
GPDMA2_Channel6_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
GPDMA2_Channel7_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
FPU_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
ICACHE_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
DCACHE1_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
DCMI_PSSI_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
FDCAN2_IT0_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
FDCAN2_IT1_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
DTS_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
RNG_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
OTFDEC1_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
AES_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
HASH_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
PKA_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
CEC_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
TIM12_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
I3C1_EV_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
I3C1_ER_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
I3C2_EV_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
I3C2_ER_IRQHandler(void);

// ----------------------------------------------------------------------------

extern uint32_t __stack;

typedef void
(*handler_ptr_t)(void);

// ----------------------------------------------------------------------------

#if defined(__GNUC__)
#pragma GCC diagnostic push

#pragma GCC diagnostic ignored "-Wpedantic"
#endif // defined(__GNUC__)

/**
 * The table of interrupt handlers. It has an explicit section name
 * and relies on the linker script to place it at the correct location
 * in memory, usually at the very beginning of the flash bank.
 */
__attribute__ ((section(".interrupt_vectors"),used))
handler_ptr_t _interrupt_vectors[] =
  {
    // Cortex-M Core Handlers
    (handler_ptr_t) &__stack,          // MSP
    Reset_Handler,                     // The reset handler

    NMI_Handler,                       // The NMI handler
    HardFault_Handler,                 // The hard fault handler
    MemManage_Handler,                 // The MPU fault handler
    BusFault_Handler,                  // The bus fault handler
    UsageFault_Handler,                // The usage fault handler
    0,                                 // Reserved
    0,                                 // Reserved
    0,                                 // Reserved
    0,                                 // Reserved
    SVC_Handler,                       // SVCall handler
    DebugMon_Handler,                  // Debug monitor handler
    0,                                 // Reserved
    PendSV_Handler,                    // The PendSV handler
    SysTick_Handler,                   // The SysTick handler

    // ------------------------------------------------------------------------
    // External Interrupts
    WWDG_IRQHandler,
    PVD_AVD_IRQHandler,
    RTC_IRQHandler,
    RTC_S_IRQHandler,
    TAMP_IRQHandler,
    RAMCFG_IRQHandler,
    FLASH_IRQHandler,
    FLASH_S_IRQHandler,
    GTZC_IRQHandler,
    RCC_IRQHandler,
    RCC_S_IRQHandler,
    EXTI0_IRQHandler,
    EXTI1_IRQHandler,
    EXTI2_IRQHandler,
    EXTI3_IRQHandler,
    EXTI4_IRQHandler,
    EXTI5_IRQHandler,
    EXTI6_IRQHandler,
    EXTI7_IRQHandler,
    EXTI8_IRQHandler,
    EXTI9_IRQHandler,
    EXTI10_IRQHandler,
    EXTI11_IRQHandler,
    EXTI12_IRQHandler,
    EXTI13_IRQHandler,
    EXTI14_IRQHandler,
    EXTI15_IRQHandler,
    GPDMA1_Channel0_IRQHandler,
    GPDMA1_Channel1_IRQHandler,
    GPDMA1_Channel2_IRQHandler,
    GPDMA1_Channel3_IRQHandler,
    GPDMA1_Channel4_IRQHandler,
    GPDMA1_Channel5_IRQHandler,
    GPDMA1_Channel6_IRQHandler,
    GPDMA1_Channel7_IRQHandler,
    IWDG_IRQHandler,
    SAES_IRQHandler,
    ADC1_IRQHandler,
    DAC1_IRQHandler,
    FDCAN1_IT0_IRQHandler,
    FDCAN1_IT1_IRQHandler,
    TIM1_BRK_IRQHandler,
    TIM1_UP_IRQHandler,
    TIM1_TRG_COM_IRQHandler,
    TIM1_CC_IRQHandler,
    TIM2_IRQHandler,
    TIM3_IRQHandler,
    TIM4_IRQHandler,
    TIM5_IRQHandler,
    TIM6_IRQHandler,
    TIM7_IRQHandler,
    I2C1_EV_IRQHandler,
    I2C1_ER_IRQHandler,
    I2C2_EV_IRQHandler,
    I2C2_ER_IRQHandler,
    SPI1_IRQHandler,
    SPI2_IRQHandler,
    SPI3_IRQHandler,
    USART1_IRQHandler,
    USART2_IRQHandler,
    USART3_IRQHandler,
    UART4_IRQHandler,
    UART5_IRQHandler,
    LPUART1_IRQHandler,
    LPTIM1_IRQHandler,
    TIM8_BRK_IRQHandler,
    TIM8_UP_IRQHandler,
    TIM8_TRG_COM_IRQHandler,
    TIM8_CC_IRQHandler,
    ADC2_IRQHandler,
    LPTIM2_IRQHandler,
    TIM15_IRQHandler,
    0,
    0,
    USB_DRD_FS_IRQHandler,
    CRS_IRQHandler,
    UCPD1_IRQHandler,
    FMC_IRQHandler,
    OCTOSPI1_IRQHandler,
    SDMMC1_IRQHandler,
    I2C3_EV_IRQHandler,
    I2C3_ER_IRQHandler,
    SPI4_IRQHandler,
    0,
    0,
    USART6_IRQHandler,
    0,
    0,
    0,
    0,
    GPDMA2_Channel0_IRQHandler,
    GPDMA2_Channel1_IRQHandler,
    GPDMA2_Channel2_IRQHandler,
    GPDMA2_Channel3_IRQHandler,
    GPDMA2_Channel4_IRQHandler,
    GPDMA2_Channel5_IRQHandler,
    GPDMA2_Channel6_IRQHandler,
    GPDMA2_Channel7_IRQHandler,
    0,
    0,
    0,
    0,
    0,
    FPU_IRQHandler,
    ICACHE_IRQHandler,
    DCACHE1_IRQHandler,
    0,
    0,
    DCMI_PSSI_IRQHandler,
    FDCAN2_IT0_IRQHandler,
    FDCAN2_IT1_IRQHandler,
    0,
    0,
    DTS_IRQHandler,
    RNG_IRQHandler,
    OTFDEC1_IRQHandler,
    AES_IRQHandler,
    HASH_IRQHandler,
    PKA_IRQHandler,
    CEC_IRQHandler,
    TIM12_IRQHandler,
    0,
    0,
    I3C1_EV_IRQHandler,
    I3C1_ER_IRQHandler,
    0,
    0,
    0,
    0,
    0,
    0,
    I3C2_EV_IRQHandler,
    I3C2_ER_IRQHandler
};

#if defined(__GNUC__)
#pragma GCC diagnostic pop
#endif // defined(__GNUC__)

// ----------------------------------------------------------------------------

/**
 * The processor ends up here if an unexpected interrupt occurs or a
 * specific handler is not present in the application code.
 * When in DEBUG, trigger a debug exception to clearly notify
 * the user of the exception and help identify the cause.
 * Otherwise enter a forever loop.
 */
void __attribute__ ((section(".after_vectors")))
Default_Handler(void)
{
#if defined(DEBUG)
  micro_os_plus_architecture_brk();
#endif
  while (1)
    {
      micro_os_plus_architecture_wfi();
    }
}

// ----------------------------------------------------------------------------
