/*
 * This file is part of the µOS++ project (https://micro-os-plus.github.io/).
 * Copyright (c) 2026 Liviu Ionescu. All rights reserved.
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose is hereby granted, under the terms of the MIT license.
 *
 * If a copy of the license was not distributed with this file, it can be
 * obtained from https://opensource.org/licenses/mit.
 */

#ifndef MICRO_OS_PLUS_DEVICE_H_
#define MICRO_OS_PLUS_DEVICE_H_

// ----------------------------------------------------------------------------

#include "micro-os-plus/architecture.h"

// Unlike the sibling SDK-linked `raspberry-pi-pico-2-riscv-sdk` platform,
// this device.h does not include the Pico SDK's `hardware/hazard3.h`
// (Hazard3-core-specific CSRs and custom-instruction intrinsics): that
// header unconditionally includes `pico.h`, which requires
// `pico/config_autogen.h`, a header normally generated by the SDK's own
// CMake build (`pico_generate_config_header`), which this platform does
// not run. Nothing here actually needs it either: this platform
// deliberately implements only minimal, Direct-mode trap handling (see
// micro-os-plus/trap-handler.h), not Hazard3's vectored `mtvec` mode or
// its `meiea`/`meipa`/`meifa`/`meinext` external-interrupt-array
// dispatch, which is the only thing `hardware/hazard3.h` would be
// needed for.

#include "micro-os-plus/rp2350/system-clock.h"
#include "micro-os-plus/trap-handler.h"

// ----------------------------------------------------------------------------

extern device::system_clock system_clock;

// ----------------------------------------------------------------------------

#endif // MICRO_OS_PLUS_DEVICE_H_

// ----------------------------------------------------------------------------
