/*
 * This file is part of the µOS++ project (https://micro-os-plus.github.io/).
 * Copyright (c) 2026 Liviu Ionescu. All rights reserved.
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose is hereby granted, under the terms of the MIT license.
 *
 * If a copy of the license was not distributed with this file, it can be
 * obtained from https://opensource.org/licenses/mit.
 */

#ifndef MICRO_OS_PLUS_RP2350_REGISTERS_H_
#define MICRO_OS_PLUS_RP2350_REGISTERS_H_

// ----------------------------------------------------------------------------

#include <cstdint>

// ----------------------------------------------------------------------------

// A minimal, core-agnostic 32-bit memory-mapped register accessor.
//
// The sibling `raspberry-pi-pico-2-arm` platform accesses peripherals via
// the Pico SDK's CMSIS `RP2350.h` structs (e.g. `SIO->GPIO_OUT_SET`), but
// that header pulls in `core_cm33.h` and is unusable from a RISC-V
// compiler. The Pico SDK's own core-agnostic alternative,
// `hardware/structs/*.h`, is not usable standalone either: it goes
// through `hardware/address_mapped.h` -> `pico.h` -> `pico/config.h` ->
// `pico/config_autogen.h`, a header normally generated by the SDK's own
// CMake build (`pico_generate_config_header`), which this platform does
// not run, since it does not configure the Pico SDK as a CMake
// subproject (see device/README.md).
//
// This macro instead builds addresses directly from the Pico SDK's plain
// `hardware/regs/*.h` headers, which are self-contained (no further
// includes) and supply a `<PERIPHERAL>_BASE` address plus an
// `<REGISTER>_OFFSET` for every register -- the same headers, and the
// same `_BITS`/`_LSB`/`_VALUE_*` bit-field macros, already used by the
// ARM platform's `device/rp2350/src/system-clock.cpp`.
#define RP2350_REG32(base, offset) \
  (*reinterpret_cast<volatile std::uint32_t*> ((base) + (offset)))

// ----------------------------------------------------------------------------

#endif // MICRO_OS_PLUS_RP2350_REGISTERS_H_

// ----------------------------------------------------------------------------
