/*
 * This file is part of the µOS++ project (https://micro-os-plus.github.io/).
 * Copyright (c) 2021 Liviu Ionescu. All rights reserved.
 *
 * Permission to use, copy, modify, and/or distribute this software
 * for any purpose is hereby granted, under the terms of the MIT license.
 *
 * If a copy of the license was not distributed with this file, it can
 * be obtained from https://opensource.org/licenses/mit.
 *
 * Major parts of the code are inspired from v1.1.8 of the Boost UT project,
 * released under the terms of the Boost Version 1.0 Software License,
 * which can be obtained from https://www.boost.org/LICENSE_1_0.txt.
 */

// ----------------------------------------------------------------------------

/**
 * @file
 * @brief C++ source file with implementations for the µTest++ test reporter
 * methods.
 *
 * @details
 * This source file contains the core implementations for the test reporting
 * facilities of the µTest++ framework. It provides the logic for formatting
 * and outputting test results, including operator overloads for a wide range
 * of value types, containers, and comparison expressions, as well as
 * structured output for logical and exception-related assertions.
 *
 * The test reporter is responsible for presenting test outcomes in a clear,
 * consistent, and expressive manner, supporting both value and pointer
 * semantics, and providing detailed diagnostics for both successful and failed
 * test cases. Special attention is given to formatting, colour highlighting,
 * and extensibility, enabling professional and readable test reports suitable
 * for embedded and general C++ development.
 *
 * All definitions reside within the `micro_os_plus::micro_test_plus`
 * namespace, ensuring clear separation from user code and minimising the risk
 * of naming conflicts.
 *
 * This file must be included when building the µTest++ library.
 */

// ----------------------------------------------------------------------------

#if defined(MICRO_OS_PLUS_INCLUDE_CONFIG_H)
#include <micro-os-plus/config.h>
#endif // MICRO_OS_PLUS_INCLUDE_CONFIG_H

#include <micro-os-plus/micro-test-plus.h>

// ----------------------------------------------------------------------------

#pragma GCC diagnostic ignored "-Waggregate-return"
#if defined(__clang__)
#pragma clang diagnostic ignored "-Wc++98-compat"
#pragma clang diagnostic ignored "-Wc++98-compat-pedantic"
#endif

namespace micro_os_plus::micro_test_plus
{
  // --------------------------------------------------------------------------

  /**
   * @details
   * The `endl` function inserts a newline character into the specified
   * `test_reporter` stream and flushes its output buffer. This operation
   * ensures that each test output line is clearly separated and immediately
   * visible, facilitating the readability and clarity of test results across
   * all test cases and folders within the µTest++ framework.
   */
  test_reporter&
  endl (test_reporter& stream)
  {
    reporter.endline ();
    return stream;
  }

  // --------------------------------------------------------------------------

  /**
   * @details
   * This method outputs the prefix for a passing test result, applying the
   * appropriate colour formatting and symbols to clearly indicate success. If
   * the output occurs within a test case, additional indentation is applied
   * for readability. The prefix includes a tick symbol (`✓`) and, if provided,
   * an associated message. Colour formatting is reset after the prefix to
   * maintain consistent output style across all test cases and folders.
   *
   * The prefix/suffix methods help shorten the code
   * generated by the template methods.
   */
  void
  test_reporter::output_pass_prefix_ (std::string& message)
  {
    *this << colors_.pass;
    if (is_in_test_case_)
      {
        *this << "  ";
      }
    *this << "  ✓ ";
    *this << colors_.none;
    if (!message.empty ())
      {
        *this << message.c_str ();
      }
  }

  /**
   * @details
   * The `endl` function acts as a stream manipulator for the `test_reporter`,
   * inserting a line ending into the output buffer and flushing the current
   * content if necessary. This ensures that test report output is clearly
   * separated and formatted, improving readability and professionalism in the
   * presentation of test results.
   *
   * Using `endl` in conjunction with the `test_reporter` output operators
   * provides a familiar and convenient mechanism for managing line breaks,
   * similar to standard C++ stream manipulators.
   *
   * The prefix/suffix methods help shorten the code
   * generated by the template methods.
   */
  void
  test_reporter::output_pass_suffix_ (void)
  {
    *this << endl;

    flush ();
  }

  /**
   * @details
   * This method outputs the prefix for a failing test result, applying the
   * appropriate colour formatting and symbols to clearly indicate failure. If
   * the output occurs within a test case, additional indentation is applied
   * for readability. The prefix includes a cross symbol (`✗`), an optional
   * message, and the label "FAILED". The source location is appended in
   * parentheses, showing the file or folder name and line number where the
   * failure occurred. Colour formatting is reset after the prefix to maintain
   * consistent output style across all test cases and folders.
   */
  void
  test_reporter::output_fail_prefix_ (
      std::string& message, const reflection::source_location& location)
  {
    *this << colors_.fail;
    if (is_in_test_case_)
      {
        *this << "  ";
      }
    *this << "  ✗ ";
    *this << colors_.none;
    if (!message.empty ())
      {
        *this << message.c_str ();
        *this << " ";
      }
    *this << colors_.fail << "FAILED" << colors_.none;
#pragma GCC diagnostic push
#if defined(__clang__)
#pragma clang diagnostic ignored "-Wsign-conversion"
#elif defined(__GNUC__)
#pragma GCC diagnostic ignored "-Wnarrowing"
#pragma GCC diagnostic ignored "-Wsign-conversion"
#endif
    *this << " (" << reflection::short_name (location.file_name ()) << ":"
          << type_traits::genuine_integral_value<unsigned int>{
               location.line ()
             };
#pragma GCC diagnostic pop
  }

  /**
   * @details
   * This method outputs the suffix for a failing test result by closing the
   * location information, appending an "aborted..." message if the test was
   * aborted, and then adding a newline to the test output. The output stream
   * is flushed to ensure immediate visibility. This approach guarantees that
   * failure results are clearly separated, promptly reported, and easily
   * distinguishable across all test cases and folders.
   */
  void
  test_reporter::output_fail_suffix_ (bool abort)
  {
    *this << ")";
    if (abort)
      {
        *this << " aborted...";
      }
    *this << endl;

    flush ();
  }

  /**
   * @details
   * This operator overload enables manipulators, such as `endl`, to be used
   * with the `test_reporter` stream in a manner similar to standard C++
   * streams. When a manipulator function is passed, it is invoked with the
   * current `test_reporter` instance, allowing for seamless integration of
   * stream operations and improved readability of test output across all test
   * cases and folders.
   */
  test_reporter&
  test_reporter::operator<< (test_reporter& (*func) (test_reporter&))
  {
    // Call the endl function.
    (*func) (*this);
    return *this;
  }

  /**
   * @details
   * This method appends a newline character to the internal output buffer of
   * the `test_reporter` and immediately flushes the stream. This ensures that
   * each line of test output is clearly separated and promptly displayed,
   * enhancing the readability and organisation of test results across all test
   * cases and folders.
   */
  void
  test_reporter::endline (void)
  {
    out_.append ("\n");
    flush ();
  }

  /**
   * @details
   * This method flushes the output buffer of the `test_reporter` by
   * synchronising it with the standard output stream. This guarantees that all
   * pending test output is immediately written and visible, ensuring prompt
   * and reliable reporting of test results across all test cases and folders.
   */
  void
  test_reporter::flush (void)
  {
    fflush (stdout); // Sync STDOUT.
  }

  /**
   * @details
   * This operator overload appends the contents of the provided
   * `std::string_view` to the internal output buffer of the `test_reporter`.
   * It enables seamless streaming of string data into the reporter, supporting
   * clear and efficient formatting of test output across all test cases and
   * folders.
   */
  test_reporter&
  test_reporter::operator<< (std::string_view sv)
  {
    out_.append (sv);
    return *this;
  }

  /**
   * @details
   * This operator overload appends the specified character to the internal
   * output buffer of the `test_reporter`. It enables efficient streaming of
   * individual characters into the reporter, supporting precise and flexible
   * formatting of test output across all test cases and folders.
   */
  test_reporter&
  test_reporter::operator<< (char c)
  {
    out_.append (1, c);
    return *this;
  }

  /**
   * @details
   * This operator overload appends the contents of the provided C-style string
   * to the internal output buffer of the `test_reporter`. It enables efficient
   * streaming of string literals and character arrays into the reporter,
   * supporting clear and flexible formatting of test output across all test
   * cases and folders.
   */
  test_reporter&
  test_reporter::operator<< (const char* s)
  {
    out_.append (s);
    return *this;
  }

  /**
   * @details
   * This operator overload appends the contents of the provided modifiable
   * C-style string to the internal output buffer of the `test_reporter`. It
   * enables efficient streaming of mutable string data into the reporter,
   * supporting clear and flexible formatting of test output across all test
   * cases and folders.
   */
  test_reporter&
  test_reporter::operator<< (char* s)
  {
    out_.append (s);
    return *this;
  }

  /**
   * @details
   * This operator overload appends the string representation of the specified
   * boolean value to the internal output buffer of the `test_reporter`. It
   * enables clear and direct streaming of boolean results into the reporter,
   * supporting precise and readable formatting of test output across all test
   * cases and folders.
   */
  test_reporter&
  test_reporter::operator<< (bool v)
  {
    out_.append (v ? "true" : "false");
    return *this;
  }

  /**
   * @details
   * This operator overload appends the string "nullptr" to the internal output
   * buffer of the `test_reporter`. It enables clear and explicit streaming of
   * null pointer values into the reporter, supporting precise and readable
   * formatting of test output across all test cases and folders.
   */
  test_reporter&
  test_reporter::operator<< (std::nullptr_t)
  {
    out_.append ("nullptr");
    return *this;
  }

  /**
   * @details
   * This operator overload appends the string representation of the specified
   * signed character to the internal output buffer of the `test_reporter`. It
   * enables precise and readable streaming of character values into the
   * reporter, supporting clear formatting of test output across all test cases
   * and folders.
   */
  test_reporter&
  test_reporter::operator<< (signed char c)
  {
    out_.append (std::to_string (c));
    out_.append ("c");
    return *this;
  }

  /**
   * @details
   * This operator overload appends the string representation of the specified
   * unsigned character to the internal output buffer of the `test_reporter`.
   * It enables precise and readable streaming of unsigned character values
   * into the reporter, supporting clear formatting of test output across all
   * test cases and folders.
   */
  test_reporter&
  test_reporter::operator<< (unsigned char c)
  {
    out_.append (std::to_string (static_cast<int> (c)));
    out_.append ("uc");
    return *this;
  }

  /**
   * @details
   * This operator overload appends the string representation of the specified
   * signed short integer to the internal output buffer of the `test_reporter`.
   * It enables precise and readable streaming of signed short values into the
   * reporter, supporting clear formatting of test output across all test cases
   * and folders.
   */
  test_reporter&
  test_reporter::operator<< (signed short v)
  {
    out_.append (std::to_string (v));
    out_.append ("s");
    return *this;
  }

  /**
   * @details
   * This operator overload appends the string representation of the specified
   * unsigned short integer to the internal output buffer of the
   * `test_reporter`. It enables precise and readable streaming of unsigned
   * short values into the reporter, supporting clear formatting of test output
   * across all test cases and folders.
   */
  test_reporter&
  test_reporter::operator<< (unsigned short v)
  {
    out_.append (std::to_string (static_cast<long> (v)));
    out_.append ("us");
    return *this;
  }

  /**
   * @details
   * This operator overload appends the string representation of the specified
   * signed integer to the internal output buffer of the `test_reporter`. It
   * enables precise and readable streaming of signed integer values into the
   * reporter, supporting clear formatting of test output across all test cases
   * and folders.
   */
  test_reporter&
  test_reporter::operator<< (signed int v)
  {
    out_.append (std::to_string (v));
    return *this;
  }

  /**
   * @details
   * This operator overload appends the string representation of the specified
   * unsigned integer to the internal output buffer of the `test_reporter`. It
   * enables precise and readable streaming of unsigned integer values into the
   * reporter, supporting clear formatting of test output across all test cases
   * and folders.
   */
  test_reporter&
  test_reporter::operator<< (unsigned int v)
  {
    out_.append (std::to_string (v));
    out_.append ("u");
    return *this;
  }

  /**
   * @details
   * This operator overload appends the string representation of the specified
   * signed long integer to the internal output buffer of the `test_reporter`.
   * It enables precise and readable streaming of signed long values into the
   * reporter, supporting clear formatting of test output across all test cases
   * and folders.
   */
  test_reporter&
  test_reporter::operator<< (signed long v)
  {
    out_.append (std::to_string (v));
    out_.append ("l");
    return *this;
  }

  /**
   * @details
   * This operator overload appends the string representation of the specified
   * unsigned long integer to the internal output buffer of the
   * `test_reporter`. It enables precise and readable streaming of unsigned
   * long values into the reporter, supporting clear formatting of test output
   * across all test cases and folders.
   */
  test_reporter&
  test_reporter::operator<< (unsigned long v)
  {
    out_.append (std::to_string (v));
    out_.append ("ul");
    return *this;
  }

  /**
   * @details
   * This operator overload appends the string representation of the specified
   * signed long long integer to the internal output buffer of the
   * `test_reporter`. It enables precise and readable streaming of signed long
   * long values into the reporter, supporting clear formatting of test output
   * across all test cases and folders.
   */
  test_reporter&
  test_reporter::operator<< (signed long long v)
  {
    out_.append (std::to_string (v));
    out_.append ("ll");
    return *this;
  }

  /**
   * @details
   * This operator overload appends the string representation of the specified
   * unsigned long long integer to the internal output buffer of the
   * `test_reporter`. It enables precise and readable streaming of unsigned
   * long long values into the reporter, supporting clear formatting of test
   * output across all test cases and folders.
   */
  test_reporter&
  test_reporter::operator<< (unsigned long long v)
  {
    out_.append (std::to_string (v));
    out_.append ("ull");
    return *this;
  }

  /**
   * @details
   * This operator overload appends the string representation of the specified
   * floating-point value to the internal output buffer of the `test_reporter`,
   * followed by the character 'f' to indicate a float type. It enables precise
   * and readable streaming of float values into the reporter, supporting clear
   * formatting of test output across all test cases and folders.
   */
  test_reporter&
  test_reporter::operator<< (float v)
  {
    out_.append (std::to_string (v));
    out_.append ("f");
    return *this;
  }

  /**
   * @details
   * This operator overload appends the string representation of the specified
   * double-precision floating-point value to the internal output buffer of the
   * `test_reporter`. It enables precise and readable streaming of double
   * values into the reporter, supporting clear formatting of test output
   * across all test cases and folders.
   */
  test_reporter&
  test_reporter::operator<< (double v)
  {
    out_.append (std::to_string (v));
    return *this;
  }

  /**
   * @details
   * This operator overload appends the string representation of the specified
   * long double-precision floating-point value to the internal output buffer
   * of the `test_reporter`, followed by the character 'l' to indicate a long
   * double type. It enables precise and readable streaming of long double
   * values into the reporter, supporting clear formatting of test output
   * across all test cases and folders.
   */
  test_reporter&
  test_reporter::operator<< (long double v)
  {
    out_.append (std::to_string (v));
    out_.append ("l");
    return *this;
  }

  /**
   * @details
   * This method marks the beginning of a test case, setting the internal state
   * to indicate that test output is now within a test case context. If there
   * is pending output and the verbosity level is set to verbose, it ensures
   * that output is properly separated and displayed, adding an empty line if
   * necessary. The output buffer is cleared and the stream is flushed to
   * guarantee that all previous output is visible before the new test case
   * begins. This approach enhances the clarity and organisation of test
   * results across all test cases and folders.
   */
  void
  test_reporter::begin_test_case ([[maybe_unused]] const char* name)
  {
    is_in_test_case_ = true;

    if (!out_.empty () && (verbosity == verbosity::verbose))
      {
        if (add_empty_line)
          {
            printf ("\n");
          }
        output ();
        add_empty_line = true;
      }

    out_.clear ();

    flush ();
  }

  /**
   * @details
   * This method marks the end of a test case, summarising its outcome and
   * outputting the results with appropriate formatting and colour coding. If
   * any checks have failed, a failure message is displayed, including the
   * number of successful and failed checks. For passing test cases, a success
   * message is shown with the total number of checks. The output is adjusted
   * according to the verbosity level, and additional spacing is managed for
   * clarity. The output buffer is cleared and the stream is flushed to ensure
   * all results are immediately visible, supporting clear and organised
   * reporting across all test cases and folders.
   */
  void
  test_reporter::end_test_case ([[maybe_unused]] const char* name)
  {
    if (verbosity == verbosity::normal || verbosity == verbosity::verbose)
      {
        if (current_test_suite->current_test_case.failed_checks > 0)
          {
            if (true /* add_empty_line */)
              {
                printf ("\n");
              }
            printf ("  • %s - test case started\n", name);
            output ();
            printf (
                "  %s✗%s %s - test case %sFAILED%s (%d %s passed, %d "
                "failed)\n",
                colors_.fail, colors_.none, name, colors_.fail, colors_.none,
                current_test_suite->current_test_case.successful_checks,
                current_test_suite->current_test_case.successful_checks == 1
                    ? "check"
                    : "checks",
                current_test_suite->current_test_case.failed_checks);
            add_empty_line = true;
          }
        else
          {
            if (add_empty_line)
              {
                printf ("\n");
              }
            if (verbosity == verbosity::verbose)
              {
                printf ("  • %s - test case started\n", name);
                output ();
                printf (
                    "  %s✓%s %s - test case passed (%d %s)\n", colors_.pass,
                    colors_.none, name,
                    current_test_suite->current_test_case.successful_checks,
                    current_test_suite->current_test_case.successful_checks
                            == 1
                        ? "check"
                        : "checks");

                add_empty_line = true;
              }
            else
              {
                printf (
                    "  %s✓%s %s - test case passed (%d %s)\n", colors_.pass,
                    colors_.none, name,
                    current_test_suite->current_test_case.successful_checks,
                    current_test_suite->current_test_case.successful_checks
                            == 1
                        ? "check"
                        : "checks");

                add_empty_line = false;
              }
          }
      }

    out_.clear ();
    flush ();

    is_in_test_case_ = false;
  }

  /**
   * @details
   * This method marks the beginning of a test suite, ensuring that output is
   * properly separated and clearly presented. If there is pending output, the
   * stream is flushed and an empty line is added for clarity. For silent or
   * quiet verbosity levels, output is suppressed. Otherwise, a message
   * indicating the start of the test suite is displayed. This approach
   * enhances the organisation and readability of test results across all test
   * cases and folders.
   */
  void
  test_reporter::begin_test_suite (const char* name)
  {
    if (add_empty_line)
      {
        flush ();
        printf ("\n");
      }

    if (verbosity == verbosity::silent || verbosity == verbosity::quiet)
      {
        add_empty_line = false;
        return;
      }

    printf ("• %s - test suite started\n", name);

    add_empty_line = true;
  }

  /**
   * @details
   * This method marks the end of a test suite, summarising the overall results
   * and presenting them with appropriate formatting and colour coding. If the
   * suite contains test cases and the verbosity is not set to quiet, an empty
   * line is added for clarity. For suites with no failed checks and at least
   * one successful check, a success message is displayed, including the number
   * of checks and test cases. Otherwise, a failure message is shown, detailing
   * the number of successful and failed checks, as well as the total number of
   * test cases. The output is immediately flushed to ensure prompt and
   * organised reporting across all test cases and folders.
   */
  void
  test_reporter::end_test_suite (test_suite_base& suite)
  {
    if (verbosity == verbosity::silent)
      {
        return;
      }

    if (suite.test_cases () > 0 && verbosity != verbosity::quiet)
      {
        printf ("\n");
        add_empty_line = true;
      }

    // Also fail if none passed.
    if (suite.failed_checks () == 0 && suite.successful_checks () != 0)
      {
        printf ("%s✓%s %s - test suite passed (%d %s in %d test %s)\n",
                colors_.pass, colors_.none, suite.name (),
                suite.successful_checks (),
                suite.successful_checks () == 1 ? "check" : "checks",
                suite.test_cases (),
                suite.test_cases () == 1 ? "case" : "cases");
      }
    else
      {
        printf ("%s✗%s %s - test suite %sFAILED%s (%d %s passed, %d failed, "
                "in %d test %s)\n",
                colors_.fail, colors_.none, suite.name (), colors_.fail,
                colors_.none, suite.successful_checks (),
                suite.successful_checks () == 1 ? "check" : "checks",
                suite.failed_checks (), suite.test_cases (),
                suite.test_cases () == 1 ? "case" : "cases");
      }
    flush ();
  }

  /**
   * @details
   * This method writes the contents of the internal output buffer to the
   * standard output stream without appending a newline character. After
   * outputting the buffer, it is cleared to prepare for subsequent output.
   * This approach ensures that test results are presented promptly and
   * efficiently, supporting clear and organised reporting across all test
   * cases and folders.
   */
  void
  test_reporter::output (void)
  {
    printf ("%s", out_.c_str ()); // No `\n` here.
    out_.clear ();
  }

  // --------------------------------------------------------------------------
} // namespace micro_os_plus::micro_test_plus

// ----------------------------------------------------------------------------
