// DO NOT EDIT!
// Automatically generated by xcdl for 'micro-os-plus.diag.trace'. (TODO)

// ----------------------------------------------------------------------------

#ifndef MICRO_OS_PLUS_SEMIHOSTING_DEFINES_H_
#define MICRO_OS_PLUS_SEMIHOSTING_DEFINES_H_

// ----------------------------------------------------------------------------

// Define the Arm semihosting call numbers and API.
#if !defined(MICRO_OS_PLUS_SEMIHOSTING_ENABLED)
#define MICRO_OS_PLUS_SEMIHOSTING_ENABLED
#endif // MICRO_OS_PLUS_SEMIHOSTING_ENABLED

// Implement all POSIX functions over the Arm semihosting API; it complements
// the newlib implementation and adds debugging support.
#if !defined(MICRO_OS_PLUS_SEMIHOSTING_SYSCALLS_ENABLED)
#define MICRO_OS_PLUS_SEMIHOSTING_SYSCALLS_ENABLED
#endif // MICRO_OS_PLUS_SEMIHOSTING_SYSCALLS_ENABLED

// Get the command line arguments via SYS_GETCMDLINE and parse them as for
// main(arc, argv); pass the return code back to the debugger when the
// application terminates.
#if !defined(MICRO_OS_PLUS_SEMIHOSTING_STARTUP_ENABLED)
#define MICRO_OS_PLUS_SEMIHOSTING_STARTUP_ENABLED
#endif // MICRO_OS_PLUS_SEMIHOSTING_STARTUP_ENABLED

// ----------------------------------------------------------------------------

#endif // MICRO_OS_PLUS_SEMIHOSTING_DEFINES_H_

// ----------------------------------------------------------------------------
