// DO NOT EDIT!
// Automatically generated by xcdl. (TODO)

// ----------------------------------------------------------------------------

#ifndef MICRO_OS_PLUS_ARCHITECTURE_DEFINES_H_
#define MICRO_OS_PLUS_ARCHITECTURE_DEFINES_H_

// ----------------------------------------------------------------------------

// The ELF entry point when the application is started by a debuggger.
#if !defined( \
    MICRO_OS_PLUS_INCLUDE_ARCHITECTURES_CORTEXM_DEBUGGER_ENTRY_POINT_ENABLED)
#define MICRO_OS_PLUS_INCLUDE_ARCHITECTURES_CORTEXM_DEBUGGER_ENTRY_POINT_ENABLED
#endif // !defined(MICRO_OS_PLUS_INCLUDE_ARCHITECTURES_CORTEXM_DEBUGGER_ENTRY_POINT_ENABLED)

// Initialise the Vector Table Offset Register (VTOR) when the application is started by a debugger.
#if !defined( \
    MICRO_OS_PLUS_INCLUDE_ARCHITECTURES_CORTEXM_DEBUGGER_ENTRY_POINT_INITIALISE_VTOR_ENABLED)
// #define MICRO_OS_PLUS_INCLUDE_ARCHITECTURES_CORTEXM_DEBUGGER_ENTRY_POINT_INITIALISE_VTOR_ENABLED
#endif // !defined(MICRO_OS_PLUS_INCLUDE_ARCHITECTURES_CORTEXM_DEBUGGER_ENTRY_POINT_INITIALISE_VTOR_ENABLED)

// The reset handler executed when the system is reset.
#if !defined(MICRO_OS_PLUS_INCLUDE_ARCHITECTURES_CORTEXM_RESET_HANDLER_ENABLED)
// #define MICRO_OS_PLUS_INCLUDE_ARCHITECTURES_CORTEXM_RESET_HANDLER_ENABLED
#endif // !defined(MICRO_OS_PLUS_INCLUDE_ARCHITECTURES_CORTEXM_RESET

// The exception handlers executed when exceptions occur.
#if !defined( \
    MICRO_OS_PLUS_INCLUDE_ARCHITECTURES_CORTEXM_EXCEPTION_HANDLERS_ENABLED)
// #define MICRO_OS_PLUS_INCLUDE_ARCHITECTURES_CORTEXM_EXCEPTION_HANDLERS_ENABLED
#endif // !defined(MICRO_OS_PLUS_INCLUDE_ARCHITECTURES_CORTEXM_EXCEPTION

// ----------------------------------------------------------------------------

#endif // MICRO_OS_PLUS_ARCHITECTURE_DEFINES_H_

// ----------------------------------------------------------------------------
